export enum TypeRate {
    AED = "AED",
    AFN = "AFN",
    ALL = "ALL",
    AMD = "AMD",
    BSD = "BSD",
    BTC = "BTC",
    EUR = "EUR",
    IRR = "IRR",
    ISK = "ISK",
    JPY = "JPY",
    KZT = "KZT",
    MXN = "MXN",
    NZD = "NZD",
    PKR = "PKR",
    PLN = "PLN",
    RSD = "RSD",
    RUB = "RUB",
    SGD = "SGD",
    TRY = "TRY",
    USD = "USD"
}